### PR TITLE
[WIP] Add CLI

### PR DESCRIPTION
**Pull request by cxhernandez**
This PR makes `deepchem-gui` a distributable package and adds an easy-to-use command-line interface:

```bash
$ deepchem-gui -h
usage: deepchem-gui [-h] [-V] command ...

deepchem-gui is a visualization tool for deep-learning models in Chemistry.

positional arguments:
  command
    server       Start a deepchem-gui server instance

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  show program's version number and exit

$ deepchem-gui server -h
usage: deepchem-gui server [-h] [-H HOST] [-P PORT] [-D DIR] [--debug DEBUG]
                           [--browser | --no-browser]

Start a deepchem-gui server instance

optional arguments:
  -h, --help            show this help message and exit
  -H HOST, --host HOST  host (default: 127.0.0.1)
  -P PORT, --port PORT  port (default: 5000)
  -D DIR, --upload-dir DIR
                        uploaded file directory (default: data/)
  --debug DEBUG         debug mode (default: True)
  --browser             launch browser (default: True)
  --no-browser

$ deepchem-gui server -P 5000
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

Hopefully this makes it easier for people to launch a server and distribute reproducibly.

### CODE REVIEW

**Comment by cxhernandez** [comment]
@prasadkawthekar: I couldn't find `ngl.dev.js` on the master branch (`ngl.js` which is supplied doesn't seem to work as-is). Is this something that you have got working locally?

**Comment by rbharath** [comment]
@cxhernandez Wow, this looks really cool! It's really nice to get the GUI into a friendly tool :+1: 

@prasadkawthekar I did a preliminary review pass and the changes look good on my end. Let me know if changes look good to you and we can go ahead and merge.

**Comment by rbharath** [comment]
@cxhernandez Quick thought, would you mind updating README.md with the description you've added to the PR? Will make it much easier for new users to launch GUI :-)

**Comment by cxhernandez** [comment]
@rbharath: done!

I would test this locally to see if it works though.... On my own machine, the server itself seems to work just fine and responds to CLI options but I was unable to render the protein in the browser. It doesn't seem to work for the master branch either— just shows a blank square where the protein should be. Not sure what the issue might be.

**Comment by prasadkawthekar** [comment]
@cxhernandez This looks great! I can test it tomorrow as I am traveling now and am without my compute.

Which browser and OS causes the protein rendering issue? I have had a similar issue with Chrome on a VM Ubuntu 16.04 running on Macbook Pro. I have not noticed this issue in Firefox on Ubuntu or even Chrome in Mac OS. It is likely to do something with WebGL not loading/running correctly.

**Comment by cxhernandez** [comment]
firefox, chrome, and safari on macOS

**Comment by cxhernandez** [comment]
Okay, @prasadkawthekar and I talked about a few issues offline today. These should be resolved now.

**Comment by cxhernandez** [comment]
BTW @prasadkawthekar, this is the error I see in my browser's console:

```javascript
gui.js:510 Uncaught TypeError: Cannot read property 'add' of undefined
    at new NGL.ResultbarWidget (gui.js:510)
    at Object.NGL.StageWidget (gui.js:268)
    at HTMLDocument.<anonymous> ((index):51)
NGL.ResultbarWidget @ gui.js:510
NGL.StageWidget @ gui.js:268
(anonymous) @ (index):51
```

Seems like `ResultbarWidget` is creating issues. I commented out anything referencing it and the GUI works.

**Comment by rbharath** [comment]
@cxhernandez @prasadkawthekar I'm going to go ahead and merge this PR in (mainly so I can play around with it for myself tomorrow :-))

**Pull request merged**
